# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_ICS_HAPTIC_DRV)		+= hapticdrv.o
hapticdrv-objs						:= haptic_drv.o rt6010.o haptic_util.o richtap_drv.o sfdc_drv.o
