
obj-$(CONFIG_OEM_BOOTINFO) += bootinfo.o
obj-$(CONFIG_OEM_BOARDID) += gpio_boardid.o
obj-$(CONFIG_OEM_HWINFO) += hwinfo.o
obj-$(CONFIG_OEM_CABLE) += cable_state.o
obj-$(CONFIG_OEM_ERRCODE) += errcode.o

